controllers:
    resource: '../src/Controller/'
    type:     annotation
#    prefix:   /
    prefix:
        pl: '' # don't prefix URLs for English, the default locale
        en: '/en'

kernel:
    resource: ../src/Kernel.php
    type: annotation
